stages:
  - build

before_script:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" "$REGISTRY"

build:
  stage: build
  script:
    - docker build -t $REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG ./docker.
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - pomortsev