stages:
  - build
  - deploy
variables:
  DOCKER_IMAGE_NAME: "$REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

build:
  stage: build
  script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" "$REGISTRY"
    - docker build -t "$DOCKER_IMAGE_NAME" ./docker
    - docker push "$DOCKER_IMAGE_NAME"
  tags:
    - pomortsev

deploy:
  stage: deploy
  script:
    - for i in $(ls *.yaml); do echo -e "\n---" && cat $i; done > config.yaml.template
    - envsubst < config.yaml.template > config.yaml
    - kubectl apply -f config.yaml
  tags:
    - pomortsev
